const menu = [
  {
    id: 1,
    title: 'Rava Upama',
    category: 'breakfast',
    price: 200,
    img: 'https://d1uz88p17r663j.cloudfront.net/original/ba32df908435796279e3d79f0d5fbdc1_Rava_Upma_-_Twist.jpg',
    desc: `Upma is a flavorful South Indian breakfast dish made from rava or cream of wheat. `,
  },
  {
    id: 2,
    title: 'butter paneer',
    category: 'lunch',
    price: 300,
    img: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2014/11/paneer-butter-masala-recipe-2.jpg',
    desc: `This Paneer Butter Masala recipe is a rich and creamy dish of paneer (cottage cheese) in a tomato, butter and cashew sauce. `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 450,
    img: 'https://sf1.mariefranceasia.com/wp-content/uploads/sites/7/2015/11/Robert-Timms-490x410.jpg',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'sandwitch',
    category: 'breakfast',
    price: 100,
    img: 'https://media-cdn.tripadvisor.com/media/photo-s/1a/36/d8/8e/hill-country-delight.jpg',
    desc: `A sandwich is a food typically consisting of vegetables, sliced cheese or meat, placed on or between slices of bread `,
  },
  {
    id: 5,
    title: 'kathi roll',
    category: 'lunch',
    price: 180,
    img: 'https://www.manjulaskitchen.com/wp-content/uploads/vegetable_kathi_roll.jpg',
    desc: `it is a skewer-roasted kebab wrapped in a paratha bread, although over the years many variants have evolved all of which now go under the generic name of kati roll.`,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 350,
    img: 'https://topsecretrecipes.com/images/product/cheesecake-factory-oreo-dream-extreme-cheesecake-copycat-recipe.jpg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 400,
    img: 'https://www.caciqueinc.com/wp-content/uploads/2019/09/BACON-WRAPPED-QUESO-STUFFED-JALAPENOS-By-Chef-Aaro%CC%81n-Sa%CC%81nchez-web-1024x683.jpg',
    desc: `Bacon-wrapped foods are foods that are prepared by being covered in bacon for additional flavour and texture.`,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 500,
    img: 'http://cdn.cnn.com/cnnnext/dam/assets/170203122442-new-mexican-flat-enchiladas.jpg',
    desc: `this cuisine has made such a mark on us that it seems like at some point or the other, everyone has a little love affair with it. `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 400,
    img: 'https://1.bp.blogspot.com/-uKbCGoLXVpc/XpvBolfotvI/AAAAAAAASg0/lqf4lRXLuhYZA8Tao_erEIpyMrFB18DUQCLcBGAsYHQ/s1600/bagels2.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 10,
    title: 'Chicken soup',
    category: 'dinner',
    price: 350,
    img: 'https://static.onecms.io/wp-content/uploads/sites/19/2019/02/26/lemony-greek-chicken-soup-1811-p16-2000.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 11,
    title: 'Idli sambhar',
    category: 'breakfast',
    price: 250,
    img: 'https://thebetterindia-static.gumlet.io/wp-content/uploads/2016/11/idli-sambar.jpg',
    desc: `It is naturally vegetarian, vegan, gluten-free and makes for one of the healthiest breakfast options served with Sambar and Coconut Chutney.`,
  },
  {
    id: 12,
    title: 'Dosa sambhar',
    category: 'breakfast',
    price: 300,
    img: 'https://i.ytimg.com/vi/x2_F2duRaQc/maxresdefault.jpg',
    desc: `Dosa are basically crispy or soft crepes made with ground and fermented lentil and rice batter.`,
  },
  {
    id: 13,
    title: 'aloo paratha',
    category: 'breakfast',
    price: 150,
    img: 'https://wordsmithkaur.com/wp-content/uploads/2018/11/Raw-Aloo-Paratha2.jpg',
    desc: `Piping-hot crisp wheat flatbreads stuffed with spiced, faintly sour mashed potatoes stuffing and relished with some tangy sour mango pickle. `,
  },
  {
    id: 14,
    title: 'eggless panckes',
    category: 'breakfast',
    price: 350,
    img: 'https://theharekrishnamovement.files.wordpress.com/2011/04/pancakes.jpg',
    desc: `These whole wheat pancake are fluffy, light and soft. These best pancakes are made with whole wheat flour and without eggs.  `,
  },
  {
    id: 15,
    title: 'biryani rice',
    category: 'lunch',
    price: 200,
    img: 'https://thecookbook.pk/wp-content/uploads/2017/07/biryani.jpg',
    desc: `It is made with Indian spices, rice, and meat and sometimes, in addition, eggs or vegetables such as potatoes in certain regional varieties.`,
  },
  {
    id: 16,
    title: 'butterscotch shake',
    category: 'shakes',
    price: 200,
    img: 'https://image.shutterstock.com/image-photo/salted-caramel-ice-cream-sundae-260nw-726198319.jpg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 17,
    title: 'cold coffee',
    category: 'shakes',
    price: 300,
    img: 'https://i.ytimg.com/vi/ZG0fuk6MUWw/maxresdefault.jpg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 18,
    title: 'Lemon chicken',
    category: 'dinner',
    price: 500,
    img: 'https://www.simplyrecipes.com/thmb/EZoTW1w87q8EOmcJW1iS16yJgB4=/1600x1057/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2010__03__lemon-chicken-horiz-a-1600-c2d39b9c29654638b1d9c6fd98b64991.jpg',
    desc: `Lemon, chicken, dried chilli, garlic and some seriously delectable sugarcane juice is all you need for this fantastic recipe`,
  },
  {
    id: 19,
    title: 'chetinad fish fry',
    category: 'dinner',
    price: 450,
    img: 'https://i.ytimg.com/vi/o8lDCY2_jyw/maxresdefault.jpg',
    desc: `Pieces of surmai fish marinated in garlic, cumin, fennel, curry leaves and tomatoes are pan-fried in refined oil and served hot.`,
  },
  {
    id: 20,
    title: 'dum aloo lukhnavi',
    category: 'dinner',
    price: 400,
    img: 'https://img-global.cpcdn.com/recipes/8a9888acef7d527f/751x532cq70/lucknowi-bharwa-aloo-recipe-main-photo.jpg',
    desc: `Take some potatoes, crumbled paneer, kasuri methi, butter, onions and some ghee.`,
  }
];
export default menu;

